In [1]:
import numpy as np
import pandas as pd

from sklearn.impute import SimpleImputer

In [2]:
diabetes = pd.read_csv('datasets/diabetes_processed.csv')
diabetes.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6.0,148.0,72.000000,35.0,219.028414,33.6,0.627,50.0,1
1,1.0,85.0,66.000000,29.0,70.341550,26.6,0.351,31.0,0
2,8.0,183.0,64.000000,32.0,270.573172,23.3,0.672,32.0,1
3,1.0,89.0,66.000000,23.0,94.000000,28.1,0.167,21.0,0
4,0.0,137.0,40.000000,35.0,168.000000,43.1,2.288,33.0,1
5,5.0,116.0,74.000000,32.0,127.840221,25.6,0.201,30.0,0
6,3.0,78.0,50.000000,32.0,88.000000,31.0,0.248,26.0,1
7,10.0,115.0,72.405184,32.0,136.570245,35.3,0.134,29.0,0
8,2.0,197.0,70.000000,45.0,543.000000,30.5,0.158,53.0,1
9,8.0,125.0,96.000000,32.0,155.571480,32.0,0.232,54.0,1

In [3]:
features = diabetes.drop('Outcome', axis=1)
labels = diabetes['Outcome']
features.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6.0,148.0,72.000000,35.0,219.028414,33.6,0.627,50.0
1,1.0,85.0,66.000000,29.0,70.341550,26.6,0.351,31.0
2,8.0,183.0,64.000000,32.0,270.573172,23.3,0.672,32.0
3,1.0,89.0,66.000000,23.0,94.000000,28.1,0.167,21.0
4,0.0,137.0,40.000000,35.0,168.000000,43.1,2.288,33.0
5,5.0,116.0,74.000000,32.0,127.840221,25.6,0.201,30.0
6,3.0,78.0,50.000000,32.0,88.000000,31.0,0.248,26.0
7,10.0,115.0,72.405184,32.0,136.570245,35.3,0.134,29.0
8,2.0,197.0,70.000000,45.0,543.000000,30.5,0.158,53.0
9,8.0,125.0,96.000000,32.0,155.571480,32.0,0.232,54.0

In [4]:
mask = np.random.randint(0, 100, size=features.shape).astype(np.bool)
mask = np.logical_not(mask)

In [5]:
features[mask] = np.nan
features.sample(15)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
420,1.0,119.0,88.000000,41.0,170.000000,45.3,0.507,26.0
318,3.0,115.0,66.000000,39.0,140.000000,38.1,0.150,28.0
464,10.0,115.0,98.000000,NaN,109.705029,24.0,1.022,34.0
37,9.0,102.0,76.000000,37.0,114.544544,32.9,0.665,46.0
286,5.0,155.0,84.000000,44.0,545.000000,38.7,0.619,34.0
546,5.0,187.0,76.000000,27.0,207.000000,43.6,1.034,53.0
176,6.0,85.0,78.000000,32.0,73.834611,31.2,0.382,42.0
645,2.0,157.0,74.000000,35.0,440.000000,NaN,0.134,30.0
193,11.0,135.0,72.405184,32.0,209.077960,52.3,0.578,40.0
554,1.0,84.0,64.000000,23.0,115.000000,36.9,0.471,28.0
111,8.0,155.0,62.000000,26.0,495.000000,34.0,0.543,46.0
455,14.0,175.0,62.000000,30.0,267.939085,33.6,0.212,38.0
137,0.0,93.0,60.000000,25.0,92.000000,28.7,0.532,22.0
60,2.0,84.0,72.405184,32.0,67.667533,32.0,0.304,21.0
296,2.0,146.0,70.000000,38.0,360.000000,28.0,0.337,29.0

In [6]:
from sklearn.pipeline import make_pipeline
from sklearn.compose import ColumnTransformer

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

In [7]:
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=0)

In [8]:
transformer = ColumnTransformer(
    transformers=[('features', SimpleImputer(strategy='mean'), [0, 1, 2, 3, 4, 5, 6, 7])]
)

In [9]:
clf = make_pipeline(transformer, DecisionTreeClassifier(max_depth=4))
clf = clf.fit(X_train, y_train)
clf.score(X_train, y_train)

0.8045602605863192

In [10]:
from sklearn.metrics import accuracy_score
y_pred = clf.predict(X_test)
accuracy_score(y_test, y_pred)

0.8051948051948052